//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Utils {

public class CancellationResponse : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CancellationResponse(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CancellationResponse obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CancellationResponse() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TransbankWrapPINVOKE.delete_CancellationResponse(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int function {
    set {
      TransbankWrapPINVOKE.CancellationResponse_function_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.CancellationResponse_function_get(swigCPtr);
      return ret;
    } 
  }

  public int responseCode {
    set {
      TransbankWrapPINVOKE.CancellationResponse_responseCode_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.CancellationResponse_responseCode_get(swigCPtr);
      return ret;
    } 
  }

  public long commerceCode {
    set {
      TransbankWrapPINVOKE.CancellationResponse_commerceCode_set(swigCPtr, value);
    } 
    get {
      long ret = TransbankWrapPINVOKE.CancellationResponse_commerceCode_get(swigCPtr);
      return ret;
    } 
  }

  public int terminalId {
    set {
      TransbankWrapPINVOKE.CancellationResponse_terminalId_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.CancellationResponse_terminalId_get(swigCPtr);
      return ret;
    } 
  }

  public int authorizationCode {
    set {
      TransbankWrapPINVOKE.CancellationResponse_authorizationCode_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.CancellationResponse_authorizationCode_get(swigCPtr);
      return ret;
    } 
  }

  public int operationID {
    set {
      TransbankWrapPINVOKE.CancellationResponse_operationID_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.CancellationResponse_operationID_get(swigCPtr);
      return ret;
    } 
  }

  public int initilized {
    set {
      TransbankWrapPINVOKE.CancellationResponse_initilized_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.CancellationResponse_initilized_get(swigCPtr);
      return ret;
    } 
  }

  public CancellationResponse() : this(TransbankWrapPINVOKE.new_CancellationResponse(), true) {
  }

}

}
