//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Utils {

public enum HexCodes {
  ACK = 0x06,
  NACK = 0x15,
  STX = 0x02,
  ETX = 0x03,
  PIPE = 0x7C
}

}
