//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Utils {

public class ParamInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ParamInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ParamInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ParamInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TransbankWrapPINVOKE.delete_ParamInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int index {
    set {
      TransbankWrapPINVOKE.ParamInfo_index_set(swigCPtr, value);
    }
    get {
      int ret = TransbankWrapPINVOKE.ParamInfo_index_get(swigCPtr);
      return ret;
    }
  }

  public int length {
    set {
      TransbankWrapPINVOKE.ParamInfo_length_set(swigCPtr, value);
    }
    get {
      int ret = TransbankWrapPINVOKE.ParamInfo_length_get(swigCPtr);
      return ret;
    }
  }

  public ParamInfo() : this(TransbankWrapPINVOKE.new_ParamInfo(), true) {
  }

}

}
