//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Utils {

public class SalesDetailResponse : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SalesDetailResponse(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SalesDetailResponse obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SalesDetailResponse() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TransbankWrapPINVOKE.delete_SalesDetailResponse(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int function {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_function_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_function_get(swigCPtr);
      return ret;
    } 
  }

  public int responseCode {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_responseCode_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_responseCode_get(swigCPtr);
      return ret;
    } 
  }

  public long commerceCode {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_commerceCode_set(swigCPtr, value);
    } 
    get {
      long ret = TransbankWrapPINVOKE.SalesDetailResponse_commerceCode_get(swigCPtr);
      return ret;
    } 
  }

  public string terminalId {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_terminalId_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_terminalId_get(swigCPtr);
      return ret;
    } 
  }

  public string ticketID {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_ticketID_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_ticketID_get(swigCPtr);
      return ret;
    } 
  }

  public string authorizationCode {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_authorizationCode_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_authorizationCode_get(swigCPtr);
      return ret;
    } 
  }

  public int amount {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_amount_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_amount_get(swigCPtr);
      return ret;
    } 
  }

  public int lastDigits {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_lastDigits_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_lastDigits_get(swigCPtr);
      return ret;
    } 
  }

  public int operationID {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_operationID_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_operationID_get(swigCPtr);
      return ret;
    } 
  }

  public string cardType {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_cardType_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_cardType_get(swigCPtr);
      return ret;
    } 
  }

  public string accountingDate {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_accountingDate_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_accountingDate_get(swigCPtr);
      return ret;
    } 
  }

  public string numberAccount {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_numberAccount_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_numberAccount_get(swigCPtr);
      return ret;
    } 
  }

  public string cardAbbr {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_cardAbbr_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_cardAbbr_get(swigCPtr);
      return ret;
    } 
  }

  public string transactionDate {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_transactionDate_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_transactionDate_get(swigCPtr);
      return ret;
    } 
  }

  public string transactionTime {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_transactionTime_set(swigCPtr, value);
    } 
    get {
      string ret = TransbankWrapPINVOKE.SalesDetailResponse_transactionTime_get(swigCPtr);
      return ret;
    } 
  }

  public int employeID {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_employeID_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_employeID_get(swigCPtr);
      return ret;
    } 
  }

  public int tip {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_tip_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_tip_get(swigCPtr);
      return ret;
    } 
  }

  public int feeAmount {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_feeAmount_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_feeAmount_get(swigCPtr);
      return ret;
    } 
  }

  public int feeNumber {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_feeNumber_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_feeNumber_get(swigCPtr);
      return ret;
    } 
  }

  public int initilized {
    set {
      TransbankWrapPINVOKE.SalesDetailResponse_initilized_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.SalesDetailResponse_initilized_get(swigCPtr);
      return ret;
    } 
  }

  public SalesDetailResponse() : this(TransbankWrapPINVOKE.new_SalesDetailResponse(), true) {
  }

}

}
