//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Utils {

public class TotalsCResponse : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TotalsCResponse(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TotalsCResponse obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TotalsCResponse() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TransbankWrapPINVOKE.delete_TotalsCResponse(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int function {
    set {
      TransbankWrapPINVOKE.TotalsCResponse_function_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsCResponse_function_get(swigCPtr);
      return ret;
    } 
  }

  public int responseCode {
    set {
      TransbankWrapPINVOKE.TotalsCResponse_responseCode_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsCResponse_responseCode_get(swigCPtr);
      return ret;
    } 
  }

  public int txCount {
    set {
      TransbankWrapPINVOKE.TotalsCResponse_txCount_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsCResponse_txCount_get(swigCPtr);
      return ret;
    } 
  }

  public int txTotal {
    set {
      TransbankWrapPINVOKE.TotalsCResponse_txTotal_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsCResponse_txTotal_get(swigCPtr);
      return ret;
    } 
  }

  public int initilized {
    set {
      TransbankWrapPINVOKE.TotalsCResponse_initilized_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsCResponse_initilized_get(swigCPtr);
      return ret;
    } 
  }

  public TotalsCResponse() : this(TransbankWrapPINVOKE.new_TotalsCResponse(), true) {
  }

}

}
