//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Utils {

public class TotalsResponse : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TotalsResponse(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TotalsResponse obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TotalsResponse() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TransbankWrapPINVOKE.delete_TotalsResponse(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int function {
    set {
      TransbankWrapPINVOKE.TotalsResponse_function_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsResponse_function_get(swigCPtr);
      return ret;
    } 
  }

  public int responseCode {
    set {
      TransbankWrapPINVOKE.TotalsResponse_responseCode_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsResponse_responseCode_get(swigCPtr);
      return ret;
    } 
  }

  public int txCount {
    set {
      TransbankWrapPINVOKE.TotalsResponse_txCount_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsResponse_txCount_get(swigCPtr);
      return ret;
    } 
  }

  public int txTotal {
    set {
      TransbankWrapPINVOKE.TotalsResponse_txTotal_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsResponse_txTotal_get(swigCPtr);
      return ret;
    } 
  }

  public int initilized {
    set {
      TransbankWrapPINVOKE.TotalsResponse_initilized_set(swigCPtr, value);
    } 
    get {
      int ret = TransbankWrapPINVOKE.TotalsResponse_initilized_get(swigCPtr);
      return ret;
    } 
  }

  public TotalsResponse() : this(TransbankWrapPINVOKE.new_TotalsResponse(), true) {
  }

}

}
