//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS {

public class TransbankWrap {
  public static int TBK_OK {
    get {
      int ret = TransbankWrapPINVOKE.TBK_OK_get();
      return ret;
    } 
  }

  public static int TBK_NOK {
    get {
      int ret = TransbankWrapPINVOKE.TBK_NOK_get();
      return ret;
    } 
  }

  public static void print_ports() {
    TransbankWrapPINVOKE.print_ports();
  }

  public static string list_ports() {
    string ret = TransbankWrapPINVOKE.list_ports();
    return ret;
  }

  public static string get_configured_port_name() {
    string ret = TransbankWrapPINVOKE.get_configured_port_name();
    return ret;
  }

  public static int open_configured_port() {
    int ret = TransbankWrapPINVOKE.open_configured_port();
    return ret;
  }

  public static int select_port(string portName) {
    int ret = TransbankWrapPINVOKE.select_port(portName);
    return ret;
  }

  public static int configure_port() {
    int ret = TransbankWrapPINVOKE.configure_port();
    return ret;
  }

  public static int get_totals() {
    int ret = TransbankWrapPINVOKE.get_totals();
    return ret;
  }

  public static int load_keys() {
    int ret = TransbankWrapPINVOKE.load_keys();
    return ret;
  }

  public static int polling() {
    int ret = TransbankWrapPINVOKE.polling();
    return ret;
  }

  public static int set_normal_mode() {
    int ret = TransbankWrapPINVOKE.set_normal_mode();
    return ret;
  }

  public static int close_port() {
    int ret = TransbankWrapPINVOKE.close_port();
    return ret;
  }

}

}
