//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Wrapper {

public enum tbk_baudrate {
  TBK_1200 = 1200,
  TBK_2400 = 2400,
  TBK_4800 = 4800,
  TBK_9600 = 9600,
  TBK_19200 = 19200,
  TBK_115200 = 115200
}

}
