//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Transbank.POS.Wrapper {

public class TransbankWrap {
  public static void print_ports() {
    TransbankWrapPINVOKE.print_ports();
  }

  public static string list_ports() {
    string ret = TransbankWrapPINVOKE.list_ports();
    return ret;
  }

  public static string get_configured_port_name() {
    string ret = TransbankWrapPINVOKE.get_configured_port_name();
    return ret;
  }

  public static tbk_return open_configured_port() {
    tbk_return ret = (tbk_return)TransbankWrapPINVOKE.open_configured_port();
    return ret;
  }

  public static tbk_return select_port(string portName) {
    tbk_return ret = (tbk_return)TransbankWrapPINVOKE.select_port(portName);
    return ret;
  }

  public static tbk_return configure_port(int baud_rate) {
    tbk_return ret = (tbk_return)TransbankWrapPINVOKE.configure_port(baud_rate);
    return ret;
  }

  public static int get_totals() {
    int ret = TransbankWrapPINVOKE.get_totals();
    return ret;
  }

  public static int load_keys() {
    int ret = TransbankWrapPINVOKE.load_keys();
    return ret;
  }

  public static tbk_return polling() {
    tbk_return ret = (tbk_return)TransbankWrapPINVOKE.polling();
    return ret;
  }

  public static int set_normal_mode() {
    int ret = TransbankWrapPINVOKE.set_normal_mode();
    return ret;
  }

  public static int close_port() {
    int ret = TransbankWrapPINVOKE.close_port();
    return ret;
  }

}

}
